package com.nexauren.audiotools.ui

import android.content.Context

object AuthStrings {
    private val values = mapOf(
        "pt" to mapOf(
            "account" to "Conta",
            "sign_in" to "Entrar",
"or" to "ou",
"continue_google" to "Continuar com Google",
            "create_account" to "Criar conta",
            "welcome_back" to "Bem-vindo de volta.",
            "create_desc" to "Cria a tua conta do Audio Tools para guardar o teu perfil.",
            "sign_in_desc" to "Entra para continuares a usar o Audio Tools.",
            "name" to "Nome",
            "email" to "E-mail",
            "password" to "Palavra-passe",
            "confirm_password" to "Confirmar palavra-passe",
            "continue" to "Continuar",
            "switch_register" to "Ainda não tens conta? Criar conta",
            "switch_login" to "Já tens uma conta? Entrar",
            "forgot_password" to "Esqueci-me da palavra-passe",
            "reset_sent" to "Enviámos um e-mail para redefinir a tua palavra-passe.",
            "logout" to "Terminar sessão",
            "logout_title" to "Terminar sessão?",
            "logout_desc" to "A tua sessão será encerrada neste dispositivo.",
            "cancel" to "Cancelar",
            "profile" to "Perfil",
            "password_reset" to "Redefinir palavra-passe",
            "password_reset_desc" to "Envia um novo e-mail de recuperação para a tua conta.",
            "signed_in_as" to "Sessão iniciada como",
            "account_ready" to "A tua conta está pronta.",
            "loading" to "A processar…",
            "invalid_email" to "Introduz um e-mail válido.",
            "password_short" to "A palavra-passe deve ter pelo menos 6 caracteres.",
            "password_mismatch" to "As palavras-passe não coincidem.",
            "name_required" to "Introduz o teu nome.",
            "auth_invalid" to "E-mail ou palavra-passe incorretos.",
            "auth_exists" to "Já existe uma conta com este e-mail.",
            "auth_weak" to "Escolhe uma palavra-passe mais forte.",
            "auth_network" to "Verifica a tua ligação à internet e tenta novamente.",
            "auth_generic" to "Não foi possível concluir a autenticação agora.",
            "auth_config" to "Não foi possível iniciar o Firebase nesta versão. Reinstala a versão mais recente do Audio Tools.",
            "auth_provider_disabled" to "O login por e-mail/senha está desativado no Firebase. Ativa esse provedor no Firebase Console.",
            "auth_invalid_config" to "A configuração do Firebase desta versão não foi aceite pelo projeto.",
            "auth_app_not_authorized" to "Esta versão do Audio Tools não está autorizada no projeto Firebase.",
            "auth_too_many" to "Muitas tentativas foram feitas. Tenta novamente mais tarde.",
            "auth_disabled" to "Esta conta está desativada.",
            "auth_internal" to "O Firebase devolveu um erro interno. Tenta novamente.",
            "reset_invalid" to "Introduz o e-mail da tua conta primeiro.",
            "profile_save_failed" to "Conta criada. O perfil será sincronizado quando houver ligação.",
            "google_cancelled" to "O login com Google foi cancelado.",
"google_unavailable" to "Não foi possível entrar com Google agora. Verifica a ligação e tenta novamente.",
"google_config" to "O login Google ainda precisa da configuração do certificado SHA-1 no Firebase para esta versão.",
"google_account_conflict" to "Já existe uma conta com este endereço. Entra com o método usado anteriormente.",
"security_note" to "A autenticação é gerida pelo Firebase. A palavra-passe não é guardada no Audio Tools."
        ),
        "en" to mapOf(
            "account" to "Account",
            "sign_in" to "Sign in",
"or" to "or",
"continue_google" to "Continue with Google",
            "create_account" to "Create account",
            "welcome_back" to "Welcome back.",
            "create_desc" to "Create your Audio Tools account to keep your profile.",
            "sign_in_desc" to "Sign in to continue using Audio Tools.",
            "name" to "Name",
            "email" to "Email",
            "password" to "Password",
            "confirm_password" to "Confirm password",
            "continue" to "Continue",
            "switch_register" to "Don't have an account? Create one",
            "switch_login" to "Already have an account? Sign in",
            "forgot_password" to "Forgot password",
            "reset_sent" to "We sent a password reset email to your address.",
            "logout" to "Sign out",
            "logout_title" to "Sign out?",
            "logout_desc" to "Your session will end on this device.",
            "cancel" to "Cancel",
            "profile" to "Profile",
            "password_reset" to "Reset password",
            "password_reset_desc" to "Send a new recovery email for your account.",
            "signed_in_as" to "Signed in as",
            "account_ready" to "Your account is ready.",
            "loading" to "Processing…",
            "invalid_email" to "Enter a valid email address.",
            "password_short" to "Password must be at least 6 characters.",
            "password_mismatch" to "Passwords do not match.",
            "name_required" to "Enter your name.",
            "auth_invalid" to "Incorrect email or password.",
            "auth_exists" to "An account already exists with this email.",
            "auth_weak" to "Choose a stronger password.",
            "auth_network" to "Check your internet connection and try again.",
            "auth_generic" to "Could not complete authentication right now.",
            "reset_invalid" to "Enter your account email first.",
            "profile_save_failed" to "Account created. The profile will sync when a connection is available.",
            "google_cancelled" to "Google sign-in was cancelled.",
"google_unavailable" to "Could not sign in with Google right now. Check your connection and try again.",
"google_config" to "Google sign-in still needs the Android certificate SHA-1 configured in Firebase for this version.",
"google_account_conflict" to "An account already exists with this address. Sign in using the method used before.",
"security_note" to "Authentication is handled by Firebase. Your password is not stored by Audio Tools."
        ),
        "fr" to mapOf(
            "account" to "Compte",
            "sign_in" to "Se connecter",
"or" to "ou",
"continue_google" to "Continuer avec Google",
            "create_account" to "Créer un compte",
            "welcome_back" to "Bon retour.",
            "create_desc" to "Crée ton compte Audio Tools pour conserver ton profil.",
            "sign_in_desc" to "Connecte-toi pour continuer à utiliser Audio Tools.",
            "name" to "Nom",
            "email" to "E-mail",
            "password" to "Mot de passe",
            "confirm_password" to "Confirmer le mot de passe",
            "continue" to "Continuer",
            "switch_register" to "Pas encore de compte ? Créer un compte",
            "switch_login" to "Déjà un compte ? Se connecter",
            "forgot_password" to "Mot de passe oublié",
            "reset_sent" to "Nous avons envoyé un e-mail de réinitialisation.",
            "logout" to "Se déconnecter",
            "logout_title" to "Se déconnecter ?",
            "logout_desc" to "Ta session sera fermée sur cet appareil.",
            "cancel" to "Annuler",
            "profile" to "Profil",
            "password_reset" to "Réinitialiser le mot de passe",
            "password_reset_desc" to "Envoyer un nouvel e-mail de récupération.",
            "signed_in_as" to "Connecté en tant que",
            "account_ready" to "Ton compte est prêt.",
            "loading" to "Traitement…",
            "invalid_email" to "Saisis une adresse e-mail valide.",
            "password_short" to "Le mot de passe doit contenir au moins 6 caractères.",
            "password_mismatch" to "Les mots de passe ne correspondent pas.",
            "name_required" to "Saisis ton nom.",
            "auth_invalid" to "E-mail ou mot de passe incorrect.",
            "auth_exists" to "Un compte existe déjà avec cet e-mail.",
            "auth_weak" to "Choisis un mot de passe plus fort.",
            "auth_network" to "Vérifie ta connexion internet puis réessaie.",
            "auth_generic" to "Impossible de terminer l’authentification.",
            "reset_invalid" to "Saisis d’abord l’e-mail de ton compte.",
            "profile_save_failed" to "Compte créé. Le profil sera synchronisé dès que possible.",
            "google_cancelled" to "La connexion Google a été annulée.",
"google_unavailable" to "Impossible de se connecter avec Google maintenant. Vérifie ta connexion puis réessaie.",
"google_config" to "La connexion Google nécessite encore le certificat SHA-1 Android configuré dans Firebase pour cette version.",
"google_account_conflict" to "Un compte existe déjà avec cette adresse. Utilise la méthode de connexion précédente.",
"security_note" to "L’authentification est gérée par Firebase. Audio Tools ne stocke pas ton mot de passe."
        ),
        "es" to mapOf(
            "account" to "Cuenta",
            "sign_in" to "Iniciar sesión",
"or" to "o",
"continue_google" to "Continuar con Google",
            "create_account" to "Crear cuenta",
            "welcome_back" to "Bienvenido de nuevo.",
            "create_desc" to "Crea tu cuenta de Audio Tools para conservar tu perfil.",
            "sign_in_desc" to "Inicia sesión para seguir usando Audio Tools.",
            "name" to "Nombre",
            "email" to "Correo electrónico",
            "password" to "Contraseña",
            "confirm_password" to "Confirmar contraseña",
            "continue" to "Continuar",
            "switch_register" to "¿No tienes cuenta? Crear cuenta",
            "switch_login" to "¿Ya tienes cuenta? Iniciar sesión",
            "forgot_password" to "He olvidado la contraseña",
            "reset_sent" to "Enviamos un correo para restablecer tu contraseña.",
            "logout" to "Cerrar sesión",
            "logout_title" to "¿Cerrar sesión?",
            "logout_desc" to "Tu sesión terminará en este dispositivo.",
            "cancel" to "Cancelar",
            "profile" to "Perfil",
            "password_reset" to "Restablecer contraseña",
            "password_reset_desc" to "Envía un nuevo correo de recuperación.",
            "signed_in_as" to "Sesión iniciada como",
            "account_ready" to "Tu cuenta está lista.",
            "loading" to "Procesando…",
            "invalid_email" to "Introduce un correo válido.",
            "password_short" to "La contraseña debe tener al menos 6 caracteres.",
            "password_mismatch" to "Las contraseñas no coinciden.",
            "name_required" to "Introduce tu nombre.",
            "auth_invalid" to "Correo o contraseña incorrectos.",
            "auth_exists" to "Ya existe una cuenta con este correo.",
            "auth_weak" to "Elige una contraseña más segura.",
            "auth_network" to "Comprueba tu conexión a internet e inténtalo de nuevo.",
            "auth_generic" to "No se pudo completar la autenticación.",
            "reset_invalid" to "Introduce primero el correo de tu cuenta.",
            "profile_save_failed" to "Cuenta creada. El perfil se sincronizará cuando haya conexión.",
            "google_cancelled" to "Se canceló el inicio de sesión con Google.",
"google_unavailable" to "No se pudo iniciar sesión con Google ahora. Comprueba tu conexión e inténtalo de nuevo.",
"google_config" to "El inicio de sesión de Google todavía necesita configurar el certificado SHA-1 de Android en Firebase para esta versión.",
"google_account_conflict" to "Ya existe una cuenta con esta dirección. Inicia sesión con el método anterior.",
"security_note" to "Firebase gestiona la autenticación. Audio Tools no almacena tu contraseña."
        ),
        "de" to mapOf(
            "account" to "Konto",
            "sign_in" to "Anmelden",
"or" to "oder",
"continue_google" to "Mit Google fortfahren",
            "create_account" to "Konto erstellen",
            "welcome_back" to "Willkommen zurück.",
            "create_desc" to "Erstelle dein Audio-Tools-Konto für dein Profil.",
            "sign_in_desc" to "Melde dich an, um Audio Tools weiter zu nutzen.",
            "name" to "Name",
            "email" to "E-Mail",
            "password" to "Passwort",
            "confirm_password" to "Passwort bestätigen",
            "continue" to "Weiter",
            "switch_register" to "Noch kein Konto? Konto erstellen",
            "switch_login" to "Schon ein Konto? Anmelden",
            "forgot_password" to "Passwort vergessen",
            "reset_sent" to "Wir haben eine E-Mail zum Zurücksetzen gesendet.",
            "logout" to "Abmelden",
            "logout_title" to "Abmelden?",
            "logout_desc" to "Deine Sitzung wird auf diesem Gerät beendet.",
            "cancel" to "Abbrechen",
            "profile" to "Profil",
            "password_reset" to "Passwort zurücksetzen",
            "password_reset_desc" to "Eine neue Wiederherstellungs-E-Mail senden.",
            "signed_in_as" to "Angemeldet als",
            "account_ready" to "Dein Konto ist bereit.",
            "loading" to "Verarbeitung…",
            "invalid_email" to "Gib eine gültige E-Mail-Adresse ein.",
            "password_short" to "Das Passwort muss mindestens 6 Zeichen lang sein.",
            "password_mismatch" to "Die Passwörter stimmen nicht überein.",
            "name_required" to "Gib deinen Namen ein.",
            "auth_invalid" to "E-Mail oder Passwort ist falsch.",
            "auth_exists" to "Für diese E-Mail existiert bereits ein Konto.",
            "auth_weak" to "Wähle ein stärkeres Passwort.",
            "auth_network" to "Prüfe deine Internetverbindung und versuche es erneut.",
            "auth_generic" to "Anmeldung konnte nicht abgeschlossen werden.",
            "reset_invalid" to "Gib zuerst die E-Mail deines Kontos ein.",
            "profile_save_failed" to "Konto erstellt. Das Profil wird bei nächster Verbindung synchronisiert.",
            "google_cancelled" to "Die Google-Anmeldung wurde abgebrochen.",
"google_unavailable" to "Google-Anmeldung ist gerade nicht möglich. Prüfe deine Verbindung und versuche es erneut.",
"google_config" to "Für die Google-Anmeldung muss das Android-SHA-1-Zertifikat dieser Version noch in Firebase konfiguriert werden.",
"google_account_conflict" to "Für diese Adresse existiert bereits ein Konto. Verwende die bisherige Anmeldemethode.",
"security_note" to "Firebase verwaltet die Authentifizierung. Audio Tools speichert dein Passwort nicht."
        )
    )

    fun t(context: Context, key: String): String =
        values[LanguageManager.get(context)]?.get(key)
            ?: values["pt"]?.get(key)
            ?: key
}
